config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  resources :problems

  get 'welcome/index'

  root 'welcome#index'

  resources :problems do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :problem
end

app/models/problem.rb
class Problem < ActiveRecord::Base
	has_many :comments, dependent: :destroy
  validates :problem_name, presence: true,
                           length: { minimum: 2 }

  # adding hash bracket behind width will determine an exact size ie: 100x100{} will crop to a square
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end


### Notes
# These two declarations enable a good bit of automatic behavior. For example, if you have an instance variable @article containing an article, you can retrieve all the comments belonging to that article as an array using @article.comments.

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  # before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
# commentsController

class CommentsController < ApplicationController
	def create
		@problem = Problem.find(params[:problem_id])
		@comment = @problem.comments.create(comment_params)
		redirect_to problem_path(@problem)
	end

	def destroy
		@problem = Problem.find(params[:problem_id])
		@comment = @problem.comments.find(params[:id])
		@comment.destroy
		redirect_to problem_path(@problem)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController  
  
  # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  # Other authentication methods are available for Rails 
  # applications. Two popular authentication add-ons for 
  # Rails are the Devise rails engine and the Authlogic gem, 
  # along with a number of others.

before_action :authenticate_user!, :except => [:show, :index]

  def index
  	@problems = Problem.all
  end

  def show
    @problem = Problem.find(params[:id])	
  end

  def new
  	@problem = Problem.new
  end

  def edit
    @problem = Problem.find(params[:id])
  end

  def create
  	@problem = Problem.new(problem_params)

    if @problem.save
    	redirect_to @problem
    else
    	render 'new'
    end
  end 

  def update
    @problem = Problem.find(params[:id])

    if @problem.update(problem_params)
    	redirect_to @problem
    else
    	render 'edit'
    end
  end

  def destroy
  	@problem = Problem.find(params[:id])
  	@problem.destroy

  	redirect_to problems_path
  end

  private 
    def problem_params
      params.require(:problem).permit(:problem_name, :problem_grade, :main_area, :description, :image )
    end
end	

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
	def main_areas
		[
			['Acre', 'Acre'],
			['Bushwhack', 'Bushwhack'],
			['Catoctin Mountain', 'Catoctin Mountain'],
			['Cat Rock', 'Cat Rock'],
			['Cunningham Falls', 'Cunningham Falls'],
			['Harpers Ferry', 'Harpers Ferry'],
			['Manor Campground', 'Manor Campground'],
			['Middlepoint', 'Middlepoint'],
			['Radio Towers', 'Radio Towers'],
			['Sugarloaf', 'Sugarloaf'],
			['Thurmont Watershed', 'Thurmont Watershed']
		]
	end

	def v_scale
	[
		['V0', 'V0'], 
		['V1', 'V1'], 
		['V2', 'V2'], 
		['V3', 'V3'], 
		['V4', 'V4'], 
		['V5', 'V5'], 
		['V6', 'V6'], 
		['V7', 'V7'], 
		['V8', 'V8'], 
		['V9', 'V9'], 
		['V10', 'V10'], 
		['V11', 'V11'], 
		['V12', 'V12'], 
		['V13', 'V13'], 
		['V14', 'V14'], 
		['V15', 'V15']
	]
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<!-- _comment.html.erb -->

<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to '[Delete Comment]', [comment.problem, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<!-- _form.html.erb -->
<%= form_for([@problem, @problem.comments.build]) do |f| %>
  <div class="comment_text">
    <%= f.label "Name" %>: <br>
    <%= f.text_field :commenter %>
  </div>
  <div class="comment_text">
    <%= f.label "Message" %>: <br>
    <%= f.text_area :body, cols: "40", rows: "2" %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag "filename" %>
<html>
	<head>
	  <title>Frederick Bouldering</title>
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<div class="wrapper">

	    <header>
				<div class="login_signup">
					<% if user_signed_in? %>
						<%= current_user.email %> | 
						<%= link_to 'Sign Out',destroy_user_session_path, method: :delete %>
					<% else %> 
						<%= link_to 'Login', new_user_session_path %>
						&nbsp; | &nbsp;
						<%= link_to 'Sign Up', new_user_registration_path %>
 					<% end %>
				</div>
	    
	    	<div class="header_text">
	    		<a href="/">Frederick Bouldering</a>
	    		<div class="notice"><%= notice %></div>
					<div class="alert"><%= alert %></div>
	    	</div>
	    </header>

			<%= yield %>

			<footer>
				<%= link_to 'All Problems', problems_path %>
				&nbsp;&nbsp;
				<%= link_to 'Add Problem', new_problem_path %>
			</footer>
		</div> <!-- close wrapper -->
	</body>
</html>

app/views/problems/_comment.html.erb
<!-- _comment.html.erb -->

<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.problem, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/problems/_form.html.erb
<!-- _form.html.erb -->
<%= form_for @problem, html: { multipart: true } do |f| %>

	<!-- form input error message -->
	<% if @problem.errors.any? %>
	  <div id="error_explanation">
	    <h4>
	      <%= pluralize(@problem.errors.count, "error") %> 
	      prohibited
	      this problem from being saved:
	    </h4>
	    <ul>
	      <% @problem.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	    </ul>
	  </div>
	<% end %>

	<!-- form labels & text -->
	<p>
	  <%= f.label 'Name:' %>
	  <%= f.text_field :problem_name %>
	</p>

	<p>
		<%= f.label 'Grade:' %>
		<%= f.select(:problem_grade, options_for_select(v_scale, :selected => f.object.problem_grade)) %>
	</p>

	<p>
		<%= f.label 'Main Area:' %>
		<%= f.select(:main_area, options_for_select(main_areas, :selected => f.object.main_area), {})
		%>
	</p>

	<p>
	  <%= f.label 'Description:' %><br>
	  <%= f.text_area :description %>
	</p>

	<p>
	  <%= f.label 'Photos:' %><br>
	  <%= f.file_field :image %>
	</p>

	<p><%= f.submit "Submit" %></p>

<% end %>

app/views/problems/edit.html.erb
<div class="navbar">
  <div class="sub_header"> Edit: <%= @problem.problem_name %> <%= @problem.problem_grade %></div>
  <div class="nav right top">
    <%= link_to 'Add Problem', new_problem_path %>
  </div>
</div>
<div>
  <%= render 'form' %>
  <%= button_to 'Delete', problem_path(@problem), method: :delete,
  	data: { confirm: 'Are you sure?'}%>
  <!-- #data: { confirm: 'Are you sure?'} ->
</div>

app/views/problems/index.html.erb
<div class="navbar">

  <div class="sub_header"> All Problems </div>
  <div class="nav right top">
    <%= link_to 'All Problems', problems_path %>
    &nbsp;&nbsp;
    <%= link_to 'Add Problem', new_problem_path %>
  </div>
  
</div>

<div id="all_problems">

  <table id="table_index">
 <!-- copy & paste -->
    <% @problems.each do |problem| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">
        <td>
          <div id="title">
          <%= link_to problem.problem_name, problem_path(problem)  %> <%= link_to problem.problem_grade, problem_path(problem) %> - @<%= problem.main_area %>
          </div>
          <div id="description"><%= problem.description %></div>
          <div id="edit"><%= link_to 'Edit', edit_problem_path(problem) %></div>
        </td>
      </tr>
    <% end %>
  <!-- copy & paste -->
  </table>
</div>  <!-- close div all_problems -->


<!-- 

    <% @problems.each do |problem| %>
      <tr class="<%= cycle('oddrow', 'evenrow') -%>">

        <td width="5%"><div id="grade"> <%= problem.problem_grade %>
          </div></td>
        <td><%= link_to problem.problem_name, problem_path(problem) %></td>
        <td><%= problem.main_area %></td>
        <td><%= problem.description %></td>
        <td><div id="edit">
          <%= link_to 'Edit', edit_problem_path(problem) %>
          <%= link_to 'Del', problem_path(problem), method: :delete %>
          </div></td>
      </tr>
    <% end %>

-->

app/views/problems/new.html.erb
<div class="navbar">
  <div class="sub_header"> Add Problem </div>
</div>

<div>
	<%= render 'form' %>
</div>

app/views/problems/show.html.erb
<div class="navbar">

  <div class="sub_header"><%= @problem.problem_name %> <%= @problem.problem_grade %></div>
  <div class="nav right top">
    <%= link_to 'Edit Problem', edit_problem_path(@problem) %>
  </div>
</div>

<div class="problem_display">
	<div class="left_display">
		<p>
			<strong>Main Area:</strong>
			<%= @problem.main_area %>
		</p>

		<p>	
		  <strong>Description:</strong>
		  <%= @problem.description %>
		</p>
	</div>

	<div class="right_display">
	<p>
		<% if @problem.image.file? %>
			<p><strong>Photos:</strong></p>
	  	<%= image_tag @problem.image.url(:medium) %>
		<% else %>
	  	<%= link_to 'Add Photo', edit_problem_path(@problem) %>
		<% end %>
	</p>

	<hr>

	<div id="comments">
		<h4>Comments</h4>
		<%= render @problem.comments %>
		<%= render 'comments/form' %>
	</div>
</section>

app/views/welcome/index.html.erb
<!-- views/welcome/index.html.erb -->
<div id="index_container">
	<p>
		Welcome to FB.
		This site aims to provide all documentation for bouldering and climbing development in and around Frederick, Maryland.
	</p>
	<p>
	<strong>Up Next..</strong>
	<li>Photo attachments for each problem.</li>
	<li>Filtering by area and/or grade.</li>
	<li>Area topos with access info.</li>
	<li>Problem properties to include public/private property.</li>
	<li>All areas with access issues will only be available to approved users.</li>
</p>
</div>